# Generated by Django 3.2.9 on 2021-11-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, unique=True)),
                ('news', models.CharField(max_length=1000, null=True)),
                ('note', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
